import type { Metadata } from 'next'
import './globals.css'
import { ClerkProvider } from '@clerk/nextjs'
import { QueryProvier } from '@/providers/query-provider'
import { SheetProvider } from '@/providers/sheet-provider'
import {Toaster} from "@/components/ui/sonner"

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<ClerkProvider afterSignOutUrl='/'>
			<html lang='en'>
				<body className={` antialiased`}>
					<QueryProvier>
						<SheetProvider/>
						<Toaster/>
						{children}
					</QueryProvier>
				</body>
			</html>
		</ClerkProvider>
	)
}
